# Generated by Django 3.2.8 on 2021-10-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('publicado', 'Publicado'), ('rascunho', 'Rascunho')], default='Rascunho', max_length=10),
        ),
    ]
